server:
  port: '8080'

spring:
  application:
    name: device-management
  #10.4. Implementando a persistÃªncia com Jakarta Persistence e Spring Data JPA - 9'30"
  datasource:
    username: sa
    url: jdbc:h2:file:~/algasensors-device-management-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    driverClassName: org.h2.Driver
    password: '123'

  #Permite acesso remoto
  h2:
    console:
      enabled: 'true'
      settings.web-allow-others: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'